### PR TITLE
Removing spring snapshot dependencies from spring data jpa

### PR DESCRIPTION
**Pull request by johanpoirier**
I excluded spring artifacts from spring data jpa dependencies.

### CODE REVIEW

**Comment by bclozel** [comment]
+1

**Comment by loicfrering** [comment]
+1, we should maybe raise an issue to Spring Data JPA?

**Comment by johanpoirier** [comment]
Yes we should.

**Comment by bclozel** [comment]
Looks like we can fix it on our side.
I dug up those bugs in SD JPA:
- [Spring Data JPA 1.1.0.RC1 references SNAPSHOT dependency spring-data-commons-core-1.3.0.BUILD-SNAPSHOT](https://jira.springsource.org/browse/DATAJPA-182)
- [spring-data-jpa 1.1.0.RELEASE pulls in spring-core 3.2.0.M1](https://jira.springsource.org/browse/DATAJPA-228)

We're probably referencing a bad artifact repository (with a messed up POM) or a snapshot repository.

**Comment by sdeleuze** [comment]
Perhaps in the Pullrequest Nexus, I will check ...

**Comment by sdeleuze** [comment]
I have removed Sanpshot repositories from RESThub virtual repository, we may check again without the Johan update in order to see if the issue still occur.

**Comment by sdeleuze** [comment]
This issue still occur after Nexus cleanup, so I merge this pull request

**Pull request merged**
