### PR TITLE
JDK6 ?

### PR DESCRIPTION
**Pull request by cexbrayat**
Even if I'd like to use jdk7 everywhere, I can't assume it will be the case for my current project. So I took a look at what needed to be changed to have resthub jdk6 compatibility : it appears to be nearly nothing. 

I would understand if you want to remain jdk7 only, but if that's not the case, consider the current PR.

### CODE REVIEW

**Comment by sdeleuze** [comment]
I am fine with having Spring Stack compatible with JDK6, and keeping archetypes and documentation pushing for JDK7 usage.

**Comment by loicfrering** [comment]
:+1:

**Comment by bclozel** [comment]
Fine by me.
We only use JDK7 syntax in the framework for diamond operator and multi-catch anyway.

Agree with @sdeleuze , we still need to push JDK7 in the archetypes - I'm pretty sure we'll need JDK7 as a requirement during the 2.x versions.

**Comment by cexbrayat** [comment]
Great! My 2 cents : I think JDK7 as a requirement tend to be a limitation for people who don't have the hand on the run environment. That's the first thing on the doc, and I've already heard : "jdk7 that's dead for us...".

That's a good thing to push it, but that shouldn't be mandatory.

**Comment by sdeleuze** [comment]
I agree. I sent a pullrequest with related documentation update : https://github.com/resthub/resthub.org/pull/62

**Pull request merged**
