### PR TITLE
Mongodb authentification

### PR DESCRIPTION
**Pull request by cexbrayat**
Added two properties to have authentification on mongodb : username and password.
By default, properties are empty, so Spring Data will still try to connect with no user (default mongodb mode).

### CODE REVIEW

**Comment by sdeleuze** [comment]
Thanks !

**Comment by cexbrayat** [comment]
My pleasure. Would be great to have a new snapshot in sonatype repo ;-)

**Comment by sdeleuze** [comment]
As soon as Brian will be back. Waiting that, I have fixed Jenkins build (http://jenkins.pullrequest.org/job/resthub-spring-stack-master/) so updated artifact are up to date on http://nexus.pullrequest.org/content/repositories/snapshots if you could update your repo url temporarily.

**Comment by cexbrayat** [comment]
That will do the trick, thanks!

**Pull request merged**
