### PR TITLE
Add new version for findall paginated API with query params

### PR DESCRIPTION
**Pull request by bmeurant**

### CODE REVIEW

**Comment by loicfrering** [comment]
I think that this is a nice step forward but still not RESTfull as "search" is not a resource. IMO the route should be:

`/entity?page=X...`

However it would require to return `Object` instead of `List<T>` or `Page<T>` for the `findAll` method...

**Comment by loicfrering** [comment]
Maybe we should just return Page<T> in all situations for consistency.

**Comment by bclozel** [comment]
I've been looking into [Spring HATEOAS](https://github.com/SpringSource/spring-hateoas/) for that.
You can add links to your Resources for pagination, relations... But it kinda sucks to rely (again!) on inheritance, since you've got to extend [Resource](https://github.com/SpringSource/spring-hateoas/blob/master/src/main/java/org/springframework/hateoas/Resource.java) for that. Traits anyone?

I'm really wondering if we should have:
- one set of controllers dealing with model entities (directly expose your model through controllers)
- one set of controllers dealing with DTOs in a "hypermedia" way.

**Comment by loicfrering** [comment]
For HATEOAS concerns as well as relations and other things we never know how to manage, I think we should seriously considering using DTO.

Yet my main concern here is about the boilerplate Mapping code we would have to write to map Entities to DTO but the main advantage is total control on what we send over the wire.

**Comment by bclozel** [comment]
+1

Maybe we should consider object mappers like [Dozer](https://github.com/DozerMapper/dozer).
Or should we stick to dedicated DTO constructors?

**Comment by loicfrering** [comment]
The mappings via API look quite interesting in Dozer!

**Comment by loicfrering** [comment]
Concerning pagination, here is an interesting article related to Spring MVC: http://www.baeldung.com/2012/01/18/rest-pagination-in-spring/.

**Comment by bmeurant** [comment]
I like the `Link HTTP header` solution but I don't know if common pagination libs will handle this.

For example, **[Backbone JS](http://backbonejs.org/)** collection wrap the server response after a fetch and expose only response body:

```
// **parse** converts a response into the hash of attributes to be `set` on
// the model. The default implementation is just to pass the response along.
parse: function(resp, xhr) {
  return resp;
},
```

To parse header, we will have to override `collection.parse()` method (ex: http://stackoverflow.com/questions/9062605/how-to-handle-custom-response-in-backbone-model).

Fortunately, **[Backbone Paginator](http://addyosmani.github.com/backbone.paginator/)** can handle this : it already overrides `parse` and we could get an xhr object and do : `xhr.getResponseHeader("Content-type");` for example.

So I think that we must check if common pagination libs (any language but mainly java and javascript) can handle this before or provide alternatives.

**Pull request merged**
